### ISSUE TITLE
`JSON.parse()` error on issues#view page.

### ISSUE THREAD

**Issue by Pierstoval** [RCRM/redmine_checklists#3]
I have an error when showing an issue in Redmine, while using this plugin, and I cannot understand what is the error exactly, just that it comes from a `JSON.parse()` error.

When I disable the plugin, everything works properly.

Here are the errors, followed by details about my environment

```
Processing by IssuesController#show as HTML
  Rendered issues/_action_menu.html.erb (19.5ms)
  Rendered plugins/redmine_checklists/app/views/checklists/_checklist_item.html.erb (0.2ms)
  (... previous line repeated multiple times)
  Rendered plugins/redmine_checklists/app/views/issues/_checklist.html.erb (44.2ms)
  Rendered plugins/redmine_spent_time_in_issue_description/app/views/issues/_time_spent_report.html.erb (189.2ms)
  Rendered issue_relations/_form.html.erb (7.0ms)
  Rendered issues/_relations.html.erb (10.9ms)
  Rendered issues/_history.html.erb (41.7ms)
  Rendered plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb within layouts/base (494.2ms)
Completed 500 Internal Server Error in 656ms (ActiveRecord: 22.1ms)

ActionView::Template::Error (A JSON text must at least contain two octets!):
     9:
    10:     <% if journal.details.any? %>
    11:     <ul class="details">
    12:       <% details_to_strings(journal.visible_details).each do |string| %>
    13:        <li><%= string %></li>
    14:       <% end %>
    15:     </ul>
  app/views/issues/_history.html.erb:12:in `block in _app_views_issues__history_html_erb__2963428427986535513_62184869804980'
  app/views/issues/_history.html.erb:2:in `each'
  app/views/issues/_history.html.erb:2:in `_app_views_issues__history_html_erb__2963428427986535513_62184869804980'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

Environment:

```env
Environment:
  Redmine version                3.1.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_custom_css             0.1.6
  redmine_dmsf                   1.5.4
  redmine_exception_handler      2.0.0.devel.eb74a043bd
  redmine_spent_time_in_issue_description 2.8.0
  redmine_zenedit                0.0.2
  redmine_checklists             3.1.2
```

Thanks for helping :)

**Comment by gravis** [comment]
same here :( 

```
Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            1.7.10.4
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.12
  redmine_checklists             3.1.2
  redmine_close_button           0.0.8
  redmine_contacts               4.0.3
  redmine_contacts_helpdesk      3.0.1
  redmine_contacts_invoices      4.0.1
  redmine_flowdock               1.2.1
  redmine_github_hook            0.2.0
  redmine_issue_reminder         0.1.0
  redmine_people                 1.0.0
  redmine_zenedit                0.0.2
```

**Comment by gravis** [comment]
Still present after upgrading to redmine_checklists  3.1.3
